classdef sensor_rig_builder < handle
% SENSOR_RIG_BUILDER Instantiates 4 Cameras, 2 Radars, and 1 LiDAR on Ego Vehicle
% =========================================================================
% Surround Perception Sensor Suite:
% 1. Front Windshield Camera: Long-range lane keeping & traffic detection (60m)
% 2. Front Bumper Near Camera: Ground plane, near pedestrians, potholes (30m)
% 3. Rear Windshield Camera: Overtaking & rear closing vehicles (50m)
% 4. Side Flank Camera: Lateral cut-ins, two-wheeler lane filtering (35m)
% 5. Front 77 GHz Long-Range Radar: Range, azimuth & Doppler velocity (100m)
% 6. Rear Collision Radar: Rear blind-spot monitoring (80m)
% 7. Roof 360-Degree LiDAR: Dense 3D spatial point cloud (60m)
% =========================================================================

    properties
        Cameras = cell(4, 1)
        Radars  = cell(2, 1)
        Lidar   = []
        CoverageConfig = struct()
    end

    methods
        function obj = sensor_rig_builder(scenario, egoActor)
            if nargin < 1, error('scenario object required'); end
            profiles = actorProfiles(scenario);

            % 1. Camera 1: Front Windshield (Telephoto & Forward Collision Monitoring)
            obj.Cameras{1} = visionDetectionGenerator('SensorIndex', 1, ...
                'SensorLocation', [2.0, 0.0], 'Height', 1.4, 'Yaw', 0.0, ...
                'MaxRange', 70.0, ...
                'UpdateInterval', 0.05, ...
                'DetectorOutput', 'Objects only', ...
                'DetectionProbability', 1.0, ...
                'FalsePositivesPerImage', 0.0, ...
                'Intrinsics', cameraIntrinsics([800 800], [320 240], [480 640]), ...
                'ActorProfiles', profiles);

            % 2. Camera 2: Left Side Mirror (Left Lateral Blind-Spot & Overtaking Monitoring)
            obj.Cameras{2} = visionDetectionGenerator('SensorIndex', 2, ...
                'SensorLocation', [0.8, 1.05], 'Height', 1.2, 'Yaw', 90.0, ...
                'MaxRange', 70.0, ...
                'UpdateInterval', 0.05, ...
                'DetectorOutput', 'Objects only', ...
                'DetectionProbability', 1.0, ...
                'FalsePositivesPerImage', 0.0, ...
                'Intrinsics', cameraIntrinsics([600 600], [320 240], [480 640]), ...
                'ActorProfiles', profiles);

            % 3. Camera 3: Rear Tailgate / Windshield (Rear-Approaching & Tailgating Monitoring)
            obj.Cameras{3} = visionDetectionGenerator('SensorIndex', 3, ...
                'SensorLocation', [-1.2, 0.0], 'Height', 1.2, 'Yaw', 180.0, ...
                'MaxRange', 70.0, ...
                'UpdateInterval', 0.05, ...
                'DetectorOutput', 'Objects only', ...
                'DetectionProbability', 1.0, ...
                'FalsePositivesPerImage', 0.0, ...
                'Intrinsics', cameraIntrinsics([600 600], [320 240], [480 640]), ...
                'ActorProfiles', profiles);

            % 4. Camera 4: Right Side Mirror (Right Cut-In, Curb VRU & Two-Wheeler Monitoring)
            obj.Cameras{4} = visionDetectionGenerator('SensorIndex', 4, ...
                'SensorLocation', [0.8, -1.05], 'Height', 1.2, 'Yaw', -90.0, ...
                'MaxRange', 70.0, ...
                'UpdateInterval', 0.05, ...
                'DetectorOutput', 'Objects only', ...
                'DetectionProbability', 1.0, ...
                'FalsePositivesPerImage', 0.0, ...
                'Intrinsics', cameraIntrinsics([600 600], [320 240], [480 640]), ...
                'ActorProfiles', profiles);

            % 5. Radar 1: Front Long-Range 77 GHz Radar
            obj.Radars{1} = drivingRadarDataGenerator('SensorIndex', 5, ...
                'MountingLocation', [3.7, 0.0, 0.3], ...
                'UpdateRate', 20.0, ...
                'FieldOfView', [60.0, 5.0], ...
                'RangeLimits', [0.0, 100.0], ...
                'AzimuthResolution', 4.0, ...
                'Profiles', profiles);

            % 6. Radar 2: Rear Collision Radar
            obj.Radars{2} = drivingRadarDataGenerator('SensorIndex', 6, ...
                'MountingLocation', [-1.0, 0.0, 0.3], ...
                'MountingAngles', [180.0, 0.0, 0.0], ...
                'UpdateRate', 20.0, ...
                'FieldOfView', [60.0, 5.0], ...
                'RangeLimits', [0.0, 80.0], ...
                'AzimuthResolution', 4.0, ...
                'Profiles', profiles);

            % 7. Roof 360-Degree LiDAR Scanner
            try
                egoId = 1;
                if nargin >= 2 && ~isempty(egoActor) && isprop(egoActor, 'ActorID')
                    egoId = egoActor.ActorID;
                end
                obj.Lidar = lidarPointCloudGenerator('SensorIndex', 7, ...
                    'SensorLocation', [1.0, 0.0], 'Height', 2.0, ...
                    'MaxRange', 60.0, ...
                    'HasRoadsInputPort', false, ...
                    'HasEgoVehicle', false, ...
                    'AzimuthLimits', [-180, 180], ...
                    'ElevationLimits', [-15, 15], ...
                    'ActorProfiles', profiles);
            catch
                obj.Lidar = [];
            end

            % Coverage metadata for visualization
            obj.CoverageConfig = struct(...
                'CamFront', struct('Pos', [2.0, 0.0],   'Range', 70.0, 'Yaw', 0.0,   'FOV', 70.0, 'Color', [0.2 0.8 1.0]), ...
                'CamLeft',  struct('Pos', [0.8, 1.05],  'Range', 70.0, 'Yaw', 90.0,  'FOV', 70.0, 'Color', [0.2 1.0 0.5]), ...
                'CamRear',  struct('Pos', [-1.2, 0.0],  'Range', 70.0, 'Yaw', 180.0, 'FOV', 70.0, 'Color', [1.0 0.8 0.2]), ...
                'CamRight', struct('Pos', [0.8, -1.05], 'Range', 70.0, 'Yaw', -90.0, 'FOV', 70.0, 'Color', [0.9 0.4 0.9]), ...
                'RadFront', struct('Pos', [3.7, 0.0],   'Range', 100.0,'Yaw', 0.0,   'FOV', 60.0, 'Color', [1.0 0.4 0.1]), ...
                'RadRear',  struct('Pos', [-1.0, 0.0],  'Range', 80.0, 'Yaw', 180.0, 'FOV', 60.0, 'Color', [0.9 0.1 0.2]));
        end

        function [camDets, radDets, ptCloud, isValid] = collect_measurements(obj, egoActor, simTime)
            camDets = {};
            radDets = {};
            ptCloud = [];
            isValid = true;

            poses = targetPoses(egoActor);
            if isempty(poses)
                return;
            end

            % Query 4 Cameras
            for c = 1:4
                if ~isempty(obj.Cameras{c})
                    try
                        [cDets, numC, isValC] = obj.Cameras{c}(poses, simTime);
                        if isValC && numC > 0
                            camDets = [camDets; cDets]; %#ok<AGROW>
                        end
                    catch
                    end
                end
            end

            % Query 2 Radars
            for r = 1:2
                if ~isempty(obj.Radars{r})
                    try
                        [rDets, numR, isValR] = obj.Radars{r}(poses, simTime);
                        if isValR && numR > 0
                            radDets = [radDets; rDets]; %#ok<AGROW>
                        end
                    catch
                    end
                end
            end

            % Query LiDAR
            if ~isempty(obj.Lidar)
                try
                    [ptCloud, isValL] = obj.Lidar(poses, simTime);
                    if ~isValL
                        ptCloud = [];
                    end
                catch
                end
            end
        end
    end
end
